name: Hourly Trigger

on:
  schedule:
    - cron: '*/1 * * * *'
# 每天整点运行一次

jobs:
  run-scripts:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 500

      - name: Install dependencies
        run: pip install arrow influxdb docopt rich langchain requests pyyaml redis aiohttp psutil invoke pyjwt python-dotenv telebot pillow tabulate pandas numpy tqdm asyncpg

      - name: Install FeiShu OpenSdk
        run: pip install https://lf3-static.bytednsdoc.com/obj/eden-cn/lmeh7phbozvhoz/base-open-sdk/baseopensdk-0.0.13-py3-none-any.whl

      - name: Install ruamel package
        run: pip install ruamel.yaml

      - name: Run scripts
        run: python3 python/gzm_play.py --token ${{ secrets.feishu_token }}

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "update internalTool config" || echo "No changes to commit"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          commit-message: "update internalTool config"
          title: "Automated PR: Updated Configuration"
          body: "This is an auto-generated PR with configuration updates."
          branch: "update-config-${{ github.run_id }}"
          labels: |
            automated-pr